name: Fuel Terminal Security Gatekeeper CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  execute-gatekeeper:
    runs-on: ubuntu-latest
    
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Esto acelera las ejecuciones futuras

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Ejecutar Gatekeeper
        run: |
          # Ejecutamos el main.py que configuramos con los inputs correctos
          python src/fuel_terminal_security_logistics_gatekeeper/main.py